export const skills = [
    {
        id:1,
        icon:"/images/skills/python.svg",
    },
    {
        id:2,
        icon:"/images/skills/django.svg",
    },
    {
        id:3,
        icon:"/images/skills/flask.svg",
    },
    {
        id:4,
        icon:"/images/skills/selenium.svg",
    },
    {
        id:5,
        icon:"/images/skills/html.svg",
    },
    {
        id:6,
        icon:"/images/skills/css.svg",
    },
    {
        id:7,
        icon:"/images/skills/tailwind.svg",
    },
    {
        id:8,
        icon:"/images/skills/js.svg",
    },
    {
        id:9,
        icon:"/images/skills/react.svg",
    },
    {
        id:10,
        icon:"/images/skills/mysql.svg",
    },
    {
        id:12,
        icon:"/images/skills/Bootstrap.svg",
    }
]